#!/usr/bin/env python3
"""Regenerate supabase/seed.sql from the bundled demo content.

The JSON files under assets/seed/ are the single source of truth for the demo
catalogue and question bank — the app reads them directly when Supabase is not
configured, and this script mirrors them into the database.

  python3 scripts/generate_seed.py
"""

from __future__ import annotations

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SEED_DIR = ROOT / "assets" / "seed"
OUTPUT = ROOT / "supabase" / "seed.sql"

QUESTS = [
    ("solve_5", "solveQuestions", 5, 20, None),
    ("correct_5", "correctAnswers", 5, 30, None),
    ("math_session", "subjectSession", 1, 50, "tyt_matematik"),
    ("daily_question", "dailyQuestion", 1, 75, None),
]

ACHIEVEMENTS = [
    ("first_step", "questionsSolved", 1, "🚀", None, 10),
    ("warming_up", "questionsSolved", 10, "🔥", None, 20),
    ("hundred", "questionsSolved", 100, "💯", None, 30),
    ("streak_start", "streakDays", 3, "📅", None, 40),
    ("one_week", "streakDays", 7, "🗓️", None, 50),
    ("on_fire", "bestCombo", 10, "⚡", None, 60),
    ("mathematician", "subjectQuestionsSolved", 100, "📐", "tyt_matematik", 70),
]


def lit(value) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def main() -> int:
    catalog = json.loads((SEED_DIR / "catalog.json").read_text(encoding="utf-8"))
    questions = json.loads((SEED_DIR / "questions.json").read_text(encoding="utf-8"))
    facts = json.loads((SEED_DIR / "facts.json").read_text(encoding="utf-8"))

    out: list[str] = [
        "-- Generated by scripts/generate_seed.py — do not edit by hand.",
        "-- Run after the migrations in supabase/migrations/.",
        "--",
        "-- Every question below is ORIGINAL demo content written for YKS Level.",
        "-- No official ÖSYM material is included. See docs/question_import.md",
        "-- before adding your own licensed content.",
        "",
        "begin;",
        "",
        "-- ------------------------------------------------------- subjects",
    ]

    for subject in catalog["subjects"]:
        out.append(
            "insert into public.subjects "
            "(code, name, exam_type, icon, color, sort_order, is_active) values ("
            f"{lit(subject['code'])}, {lit(subject['name'])}, "
            f"{lit(subject['exam_type'])}::exam_type, {lit(subject['icon'])}, "
            f"{lit(subject['color'])}, {subject['sort_order']}, "
            f"{lit(subject['is_active'])}) "
            "on conflict (code) do update set "
            "name = excluded.name, exam_type = excluded.exam_type, "
            "icon = excluded.icon, color = excluded.color, "
            "sort_order = excluded.sort_order, is_active = excluded.is_active;"
        )

    out += ["", "-- --------------------------------------------------------- topics"]
    for subject in catalog["subjects"]:
        for topic in subject["topics"]:
            out.append(
                "insert into public.topics (subject_id, code, name, sort_order) values ("
                f"(select id from public.subjects where code = {lit(subject['code'])}), "
                f"{lit(topic['code'])}, {lit(topic['name'])}, {topic['sort_order']}) "
                "on conflict (subject_id, code) do update set "
                "name = excluded.name, sort_order = excluded.sort_order;"
            )

    out += ["", "-- --------------------------------------------------- daily quests"]
    for code, kind, target, xp, subject_code in QUESTS:
        out.append(
            "insert into public.daily_quests "
            "(code, kind, target, xp_reward, subject_code) values ("
            f"{lit(code)}, {lit(kind)}, {target}, {xp}, {lit(subject_code)}) "
            "on conflict (code) do update set "
            "kind = excluded.kind, target = excluded.target, "
            "xp_reward = excluded.xp_reward, subject_code = excluded.subject_code;"
        )

    out += ["", "-- ---------------------------------------------------- achievements"]
    for code, kind, threshold, icon, subject_code, order in ACHIEVEMENTS:
        out.append(
            "insert into public.achievements "
            "(code, kind, threshold, icon, subject_code, sort_order) values ("
            f"{lit(code)}, {lit(kind)}, {threshold}, {lit(icon)}, "
            f"{lit(subject_code)}, {order}) "
            "on conflict (code) do update set "
            "kind = excluded.kind, threshold = excluded.threshold, "
            "icon = excluded.icon, sort_order = excluded.sort_order;"
        )

    out += ["", "-- ------------------------------------------------------ app content"]
    out.append(
        "delete from public.app_content where content_type = 'daily_fact';"
    )
    for fact in facts["facts"]:
        out.append(
            "insert into public.app_content "
            "(content_type, subject_code, body) values ("
            f"'daily_fact', {lit(fact.get('subject'))}, {lit(fact['text'])});"
        )

    out += ["", "-- --------------------------------------------- demo question bank"]
    for question in questions["questions"]:
        topic_code = question.get("topic")
        topic_expr = (
            "null"
            if not topic_code
            else (
                "(select t.id from public.topics t "
                "join public.subjects s on s.id = t.subject_id "
                f"where s.code = {lit(question['subject'])} "
                f"and t.code = {lit(topic_code)})"
            )
        )
        out.append(
            "insert into public.questions ("
            "external_id, exam_type, subject_id, topic_id, year, source_type, "
            "question_text, option_a, option_b, option_c, option_d, option_e, "
            "correct_option, explanation, difficulty) values ("
            f"{lit(question['id'])}, {lit(question['exam_type'])}::exam_type, "
            f"(select id from public.subjects where code = {lit(question['subject'])}), "
            f"{topic_expr}, {lit(question.get('year'))}, "
            f"{lit(question.get('source_type', 'demo'))}, "
            f"{lit(question['question_text'])}, {lit(question['option_a'])}, "
            f"{lit(question['option_b'])}, {lit(question['option_c'])}, "
            f"{lit(question['option_d'])}, {lit(question.get('option_e'))}, "
            f"{lit(question['correct_option'])}, "
            f"{lit(question.get('explanation'))}, "
            f"{lit(question.get('difficulty', 'medium'))}::question_difficulty"
            ") on conflict (external_id) do nothing;"
        )

    out += ["", "commit;", ""]
    OUTPUT.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(questions['questions'])} questions)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
