#!/usr/bin/env python3
"""Import a question bank into the YKS Level Supabase project.

Reads CSV or JSON, validates every row, and either prints SQL you can paste
into the Supabase SQL editor or uploads directly through the REST API.

  # Generate SQL (safe, no credentials needed)
  python3 scripts/import_questions.py --input questions.csv --sql out.sql

  # Upload straight to Supabase (needs the SERVICE ROLE key)
  export SUPABASE_URL="https://xxxx.supabase.co"
  export SUPABASE_SERVICE_ROLE_KEY="eyJ..."
  python3 scripts/import_questions.py --input questions.csv --upload

COPYRIGHT: only import questions you have the rights to distribute. Official
ÖSYM exam questions must never be scraped or imported. See
docs/question_import.md.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import sys
import urllib.error
import urllib.request
from typing import Any

REQUIRED_FIELDS = [
    "exam_type",
    "subject",
    "question_text",
    "option_a",
    "option_b",
    "option_c",
    "option_d",
    "correct_option",
]

OPTIONAL_FIELDS = [
    "id",
    "topic",
    "year",
    "option_e",
    "explanation",
    "difficulty",
    "source_type",
    "question_image_url",
]

VALID_EXAM_TYPES = {"TYT", "AYT"}
VALID_OPTIONS = {"A", "B", "C", "D", "E"}
VALID_DIFFICULTIES = {"easy", "medium", "hard"}

BATCH_SIZE = 100


class ValidationError(Exception):
    pass


def read_rows(path: str) -> list[dict[str, Any]]:
    if path.lower().endswith(".json"):
        with open(path, encoding="utf-8") as handle:
            payload = json.load(handle)
        rows = payload["questions"] if isinstance(payload, dict) else payload
        if not isinstance(rows, list):
            raise ValidationError("JSON must be a list or {'questions': [...]}")
        return rows

    with open(path, encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def clean(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def validate(row: dict[str, Any], index: int) -> dict[str, Any]:
    where = f"row {index + 1}"

    for field in REQUIRED_FIELDS:
        if not clean(row.get(field)):
            raise ValidationError(f"{where}: missing required field '{field}'")

    exam_type = clean(row["exam_type"]).upper()
    if exam_type not in VALID_EXAM_TYPES:
        raise ValidationError(
            f"{where}: exam_type must be one of {sorted(VALID_EXAM_TYPES)}"
        )

    correct = clean(row["correct_option"]).upper()
    if correct not in VALID_OPTIONS:
        raise ValidationError(
            f"{where}: correct_option must be one of {sorted(VALID_OPTIONS)}"
        )

    option_e = clean(row.get("option_e"))
    if correct == "E" and not option_e:
        raise ValidationError(f"{where}: correct_option is E but option_e is empty")

    difficulty = (clean(row.get("difficulty")) or "medium").lower()
    if difficulty not in VALID_DIFFICULTIES:
        raise ValidationError(
            f"{where}: difficulty must be one of {sorted(VALID_DIFFICULTIES)}"
        )

    year_raw = clean(row.get("year"))
    year = None
    if year_raw is not None:
        try:
            year = int(year_raw)
        except ValueError as error:
            raise ValidationError(f"{where}: year must be an integer") from error

    return {
        "external_id": clean(row.get("id")),
        "exam_type": exam_type,
        "subject_code": clean(row["subject"]),
        "topic_code": clean(row.get("topic")),
        "year": year,
        "source_type": clean(row.get("source_type")) or "licensed",
        "question_text": clean(row["question_text"]),
        "question_image_url": clean(row.get("question_image_url")),
        "option_a": clean(row["option_a"]),
        "option_b": clean(row["option_b"]),
        "option_c": clean(row["option_c"]),
        "option_d": clean(row["option_d"]),
        "option_e": option_e,
        "correct_option": correct,
        "explanation": clean(row.get("explanation")),
        "difficulty": difficulty,
    }


def sql_literal(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def to_sql(questions: list[dict[str, Any]]) -> str:
    lines = [
        "-- Generated by scripts/import_questions.py — do not edit by hand.",
        "-- Subject and topic codes are resolved against the catalogue, so run",
        "-- supabase/seed.sql first.",
        "",
    ]
    for question in questions:
        topic_expr = (
            "null"
            if question["topic_code"] is None
            else (
                "(select t.id from public.topics t "
                "join public.subjects s on s.id = t.subject_id "
                f"where s.code = {sql_literal(question['subject_code'])} "
                f"and t.code = {sql_literal(question['topic_code'])})"
            )
        )
        lines.append(
            "insert into public.questions ("
            "external_id, exam_type, subject_id, topic_id, year, source_type, "
            "question_text, question_image_url, option_a, option_b, option_c, "
            "option_d, option_e, correct_option, explanation, difficulty) values ("
            f"{sql_literal(question['external_id'])}, "
            f"{sql_literal(question['exam_type'])}::exam_type, "
            "(select id from public.subjects where code = "
            f"{sql_literal(question['subject_code'])}), "
            f"{topic_expr}, "
            f"{sql_literal(question['year'])}, "
            f"{sql_literal(question['source_type'])}, "
            f"{sql_literal(question['question_text'])}, "
            f"{sql_literal(question['question_image_url'])}, "
            f"{sql_literal(question['option_a'])}, "
            f"{sql_literal(question['option_b'])}, "
            f"{sql_literal(question['option_c'])}, "
            f"{sql_literal(question['option_d'])}, "
            f"{sql_literal(question['option_e'])}, "
            f"{sql_literal(question['correct_option'])}, "
            f"{sql_literal(question['explanation'])}, "
            f"{sql_literal(question['difficulty'])}::question_difficulty"
            ") on conflict (external_id) do nothing;"
        )
    lines.append("")
    return "\n".join(lines)


def rest_call(url: str, key: str, method: str, path: str, body: Any = None) -> Any:
    request = urllib.request.Request(
        f"{url.rstrip('/')}/rest/v1/{path}",
        method=method,
        data=None if body is None else json.dumps(body).encode("utf-8"),
        headers={
            "apikey": key,
            "Authorization": f"Bearer {key}",
            "Content-Type": "application/json",
            "Prefer": "return=representation,resolution=merge-duplicates",
        },
    )
    with urllib.request.urlopen(request) as response:
        payload = response.read().decode("utf-8")
        return json.loads(payload) if payload else []


def upload(questions: list[dict[str, Any]], url: str, key: str) -> None:
    subjects = rest_call(url, key, "GET", "subjects?select=id,code")
    topics = rest_call(
        url, key, "GET", "topics?select=id,code,subjects(code)"
    )

    subject_ids = {row["code"]: row["id"] for row in subjects}
    topic_ids = {
        ((row.get("subjects") or {}).get("code"), row["code"]): row["id"]
        for row in topics
    }

    payload = []
    for question in questions:
        subject_id = subject_ids.get(question["subject_code"])
        if subject_id is None:
            raise ValidationError(
                f"unknown subject code '{question['subject_code']}' — "
                "run supabase/seed.sql first"
            )
        record = {
            key_: value
            for key_, value in question.items()
            if key_ not in {"subject_code", "topic_code"}
        }
        record["subject_id"] = subject_id
        record["topic_id"] = topic_ids.get(
            (question["subject_code"], question["topic_code"])
        )
        payload.append(record)

    for start in range(0, len(payload), BATCH_SIZE):
        batch = payload[start : start + BATCH_SIZE]
        rest_call(url, key, "POST", "questions?on_conflict=external_id", batch)
        print(f"uploaded {start + len(batch)}/{len(payload)}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, help="CSV or JSON file")
    parser.add_argument("--sql", help="write SQL to this path instead of uploading")
    parser.add_argument("--upload", action="store_true", help="upload via REST")
    parser.add_argument("--supabase-url", default=os.environ.get("SUPABASE_URL"))
    parser.add_argument(
        "--service-key", default=os.environ.get("SUPABASE_SERVICE_ROLE_KEY")
    )
    args = parser.parse_args()

    try:
        rows = read_rows(args.input)
        questions = [validate(row, index) for index, row in enumerate(rows)]
    except (ValidationError, OSError, json.JSONDecodeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    print(f"validated {len(questions)} question(s)")

    if args.upload:
        if not args.supabase_url or not args.service_key:
            print(
                "error: --upload needs SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY",
                file=sys.stderr,
            )
            return 1
        try:
            upload(questions, args.supabase_url, args.service_key)
        except (ValidationError, urllib.error.HTTPError, urllib.error.URLError) as error:
            print(f"error: {error}", file=sys.stderr)
            return 1
        print("done")
        return 0

    sql = to_sql(questions)
    if args.sql:
        with open(args.sql, "w", encoding="utf-8") as handle:
            handle.write(sql)
        print(f"wrote {args.sql}")
    else:
        print(sql)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
